{"cells":[{"cell_type":"code","execution_count":1,"metadata":{"id":"JaXmhxZ2xx84"},"outputs":[{"name":"stdout","output_type":"stream","text":["Note: you may need to restart the kernel to use updated packages.\n"]},{"name":"stderr","output_type":"stream","text":["Traceback (most recent call last):\n","  File \"C:\\Users\\win\\anaconda3\\lib\\runpy.py\", line 194, in _run_module_as_main\n","    return _run_code(code, main_globals, None,\n","  File \"C:\\Users\\win\\anaconda3\\lib\\runpy.py\", line 87, in _run_code\n","    exec(code, run_globals)\n","  File \"C:\\Users\\win\\anaconda3\\lib\\site-packages\\pip\\__main__.py\", line 21, in <module>\n","    from pip._internal.cli.main import main as _main\n","  File \"C:\\Users\\win\\anaconda3\\lib\\site-packages\\pip\\_internal\\cli\\main.py\", line 8, in <module>\n","    from pip._internal.cli.autocompletion import autocomplete\n","  File \"C:\\Users\\win\\anaconda3\\lib\\site-packages\\pip\\_internal\\cli\\autocompletion.py\", line 9, in <module>\n","    from pip._internal.cli.main_parser import create_main_parser\n","  File \"C:\\Users\\win\\anaconda3\\lib\\site-packages\\pip\\_internal\\cli\\main_parser.py\", line 7, in <module>\n","    from pip._internal.cli import cmdoptions\n","  File \"C:\\Users\\win\\anaconda3\\lib\\site-packages\\pip\\_internal\\cli\\cmdoptions.py\", line 22, in <module>\n","    from pip._internal.cli.progress_bars import BAR_TYPES\n","  File \"C:\\Users\\win\\anaconda3\\lib\\site-packages\\pip\\_internal\\cli\\progress_bars.py\", line 9, in <module>\n","    from pip._internal.utils.logging import get_indentation\n","  File \"C:\\Users\\win\\anaconda3\\lib\\site-packages\\pip\\_internal\\utils\\logging.py\", line 14, in <module>\n","    from pip._internal.utils.misc import ensure_dir\n","  File \"C:\\Users\\win\\anaconda3\\lib\\site-packages\\pip\\_internal\\utils\\misc.py\", line 29, in <module>\n","    from pip._internal.locations import get_major_minor_version, site_packages, user_site\n","  File \"C:\\Users\\win\\anaconda3\\lib\\site-packages\\pip\\_internal\\locations\\__init__.py\", line 9, in <module>\n","    from . import _distutils, _sysconfig\n","  File \"C:\\Users\\win\\anaconda3\\lib\\site-packages\\pip\\_internal\\locations\\_sysconfig.py\", line 8, in <module>\n","    from pip._internal.exceptions import InvalidSchemeCombination, UserInstallationInvalid\n","ImportError: cannot import name 'InvalidSchemeCombination' from 'pip._internal.exceptions' (C:\\Users\\win\\anaconda3\\lib\\site-packages\\pip\\_internal\\exceptions.py)\n"]}],"source":["pip install face_recognition"]},{"cell_type":"code","execution_count":2,"metadata":{},"outputs":[{"ename":"ModuleNotFoundError","evalue":"No module named 'face_recognition'","output_type":"error","traceback":["\u001b[1;31m---------------------------------------------------------------------------\u001b[0m","\u001b[1;31mModuleNotFoundError\u001b[0m                       Traceback (most recent call last)","\u001b[1;32m<ipython-input-2-2b43a4c2b73a>\u001b[0m in \u001b[0;36m<module>\u001b[1;34m\u001b[0m\n\u001b[1;32m----> 1\u001b[1;33m \u001b[1;32mimport\u001b[0m \u001b[0mface_recognition\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m      2\u001b[0m \u001b[1;32mimport\u001b[0m \u001b[0mcv2\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m      3\u001b[0m \u001b[1;32mfrom\u001b[0m \u001b[0mPIL\u001b[0m \u001b[1;32mimport\u001b[0m \u001b[0mImage\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mImageOps\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m      4\u001b[0m \u001b[1;32mimport\u001b[0m \u001b[0mmatplotlib\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mpyplot\u001b[0m \u001b[1;32mas\u001b[0m \u001b[0mplt\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m      5\u001b[0m \u001b[1;32mimport\u001b[0m \u001b[0mos\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n","\u001b[1;31mModuleNotFoundError\u001b[0m: No module named 'face_recognition'"]}],"source":["import face_recognition\n","import cv2\n","from PIL import Image, ImageOps\n","import matplotlib.pyplot as plt\n","import os\n","import base64\n","from io import BytesIO\n"]},{"cell_type":"code","execution_count":null,"metadata":{},"outputs":[],"source":["# Image input\n","\n","new_img = Image.open('/content/drive/MyDrive/python_ML/face/face.jpg')\n","\n","# im_flip = ImageOps.flip(im)\n","width, height = new_img.size\n","resized = new_img.resize((width//3, height//3))\n","\n","# # 현재사진이 뒤집혀있어서, 뒤집은 코드\n","# resized_flip = ImageOps.flip(resized)\n","\n","# plt.imshow(resized) # Resized img check\n","\n","# save resized img\n","resized_save = resized.save('resized.jpg' )\n","im = cv2.imread('/content/resized.jpg')\n","# print(im.shape)"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"nq-09Bw9x1c8"},"outputs":[],"source":["\n","\n","# Load the jpg file into a numpy array\n","image = face_recognition.load_image_file('/content/resized.jpg')\n","\n","\n","face_locations = face_recognition.face_locations(image, number_of_times_to_upsample=3, model=\"cnn\")\n","\n","\n","list = []\n","for face_location in face_locations:\n","    # Print the location of each face in this image\n","    top, right, bottom, left = face_location\n","    face_image = image[top:bottom, left:right]\n","   \n","    pil_image = Image.fromarray(face_image)\n","    # pil_image.show(face_image)\n","    # plt.imshow(pil_image)\n","    pil_image.save('indi.jpg')\n","\n","    list.append(pil_image)\n","\n","\n","\n"," \n","    # print(\"A face is located at pixel location Top: {}, Left: {}, Bottom: {}, Right: {}\".format(top, left, bottom, right))\n","\n","# print(list)\n","\n","list_test = []\n","\n","data = {}\n","\n","\n","\n","for i in range(len(list)):\n","    buffered = BytesIO()\n","    list[i].save(buffered, format=\"JPEG\")\n","    img_str = base64.b64encode(buffered.getvalue())\n","    list_test.append(img_str)\n","\n","    data[f'image{i+1}'] = img_str.decode('utf-8')\n","\n","print(data)\n","\n","    \n","    # You can access the actual face itself like this:\n","  "]}],"metadata":{"colab":{"authorship_tag":"ABX9TyMSoIsNoJlK16pY0WH0TlxI","collapsed_sections":[],"name":"face_detection.ipynb","provenance":[]},"kernelspec":{"display_name":"Python 3","name":"python3"},"language_info":{"codemirror_mode":{"name":"ipython","version":3},"file_extension":".py","mimetype":"text/x-python","name":"python","nbconvert_exporter":"python","pygments_lexer":"ipython3","version":"3.8.8"}},"nbformat":4,"nbformat_minor":0}
